### ISSUE TITLE
windows 下測試無法連結onedrive 服務器

### ISSUE THREAD

**Issue by yangwengl** [ESTLing/onedrive#1]
你好,github上看到你的 onedrive代碼,覺得很有意思,在windows上調通執行,測試發現無法與服務器建立連接,錯誤在http.c文件 72行
connect(client_fd, (struct sockaddr*)(&serves_addr), sizeof(struct sockaddr)) == -1

也無法建立SSL連接
SSL_connect(ssl) == -1

**Comment by ESTLing** [comment]
我问的不是VC6什么的啊……这是Linux下编写的基于POSIX标准的程序，其中包含的头文件许多是windows上没有的，没有用msys2之类的的类Linux环境的话，肯定运行不了。

**Comment by yangwengl** [comment]
sorry阿,linux 不太熟悉.我在 windows 下稍微調整一下就可以編譯執行了,很多頭文件windows下都有對應的,openssl庫應該也不會有影響,執行的時候發現無法連結onedrive 服務器

---

寄件者: 白鬼泠 notifications@github.com
寄件日期: 2016年7月27日 下午 04:15:17
收件者: ESTLing/onedrive
副本: yangwengl; Author
主旨: Re: [ESTLing/onedrive] windows 下測試無法連結onedrive 服務器 (#1)

我?的不是VC6什么的啊……?是Linux下??的基于POSIX?准的程序，其中包含的?文件?多是windows上?有的，?有用msys2之?的的?Linux?境的?，肯定?行不了。

**Comment by ESTLing** [comment]
这样啊……
connect函数出错是指返回值为-1还是有其他异常呢？如果是-1的话，应该会退出，执行不到SSL_connect的吧？

**Comment by ESTLing** [comment]
我现在没有VC的那套开发工具，没办法帮你调试了。不过根据现况来看，有几个可能的问题点：
1. windows的网络编程在使用socket之前需要调用WSAStartup函数，关闭socket函数为closesocket，这两处和linux下的不同。
2. connect执行时间过长的话可能是windows防火墙问题，这个可以用GetLastError函数查一下错误码查出来的。
这是我暂时能想到的，希望能帮到你。
